services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rust
      POSTGRES_PASSWORD: rust
      POSTGRES_DB: ruststats
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    environment:
      API_KEY: ${API_KEY:-tJXYYhqC-r4B9hv_DruWo!2o9.wVUx}
      DB_URL: postgresql+psycopg2://rust:rust@db:5432/ruststats
      CORS_ORIGINS: "*"
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiMzk0N2E3NDI0MTRlYmNjOTNjMTUzN2I3NzMwMzVmYmIiLCJ0IjoiZThkYTUyMjItOTkzYS00MDI0LWFhODEtN2VlZDhiNmYxZGVjIiwicyI6Ill6QmhOV1ZqTW1NdFlqTTFPQzAwTWpoakxXRmtOV010T1RBNVlqQmxZamhtTURJdyJ9
    restart: unless-stopped
    depends_on:
      - web


volumes:
  dbdata:
